In [4]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.pipeline import Pipeline

# Dataset
X = np.array([[20, 30000], [30, 50000], [40, 70000]])
y = np.array([0, 1, 1])

# Langkah 1: Bagi data menjadi pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Langkah 2: Buat pipeline (preprocessing + model)
pipeline = Pipeline([
    ('scaler', StandardScaler()),  # Normalisasi data
    ('mlp', MLPClassifier(hidden_layer_sizes=(2,), activation='logistic', 
                          solver='sgd', learning_rate_init=0.1, 
                          max_iter=1000, random_state=42))
])

# Langkah 3: Latih model
pipeline.fit(X_train, y_train)

# Langkah 4: Prediksi dan evaluasi
y_pred = pipeline.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Langkah 5: Cross-validation
cv_scores = cross_val_score(pipeline, X, y, cv=2, scoring='accuracy')

# Cetak hasil
print("Data Pelatihan (setelah normalisasi):")
print(pipeline.named_steps['scaler'].transform(X_train))
print("\nPrediksi pada Data Pengujian:", y_pred)
print("Akurasi:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("\nCross-Validation Scores:", cv_scores)
print("Rata-rata CV Score:", cv_scores.mean())

# Langkah 6: Inspeksi bobot dan bias
mlp = pipeline.named_steps['mlp']
print("\nBobot Hidden Layer:\n", mlp.coefs_[0])
print("Bias Hidden Layer:\n", mlp.intercepts_[0])
print("Bobot Output Layer:\n", mlp.coefs_[1])
print("Bias Output Layer:\n", mlp.intercepts_[1])

Data Pelatihan (setelah normalisasi):
[[-1. -1.]
 [ 1.  1.]]

Prediksi pada Data Pengujian: [1]
Akurasi: 0.0
Confusion Matrix:
 [[0 1]
 [0 0]]

Cross-Validation Scores: [0.5 1. ]
Rata-rata CV Score: 0.75

Bobot Hidden Layer:
 [[-0.19308004  0.58381062]
 [ 0.31122582  0.08712041]]
Bias Hidden Layer:
 [ 0.51009533 -0.70000965]
Bobot Output Layer:
 [[-2.36039941]
 [-0.85967851]]
Bias Output Layer:
 [-3.70211169]


c:\Users\ariop\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
