
### Soal: Prediksi Kepuasan Pelanggan Restoran

**Latar Belakang Kasus**:  
Anda adalah seorang _data scientist_ di sebuah restoran cepat saji. Restoran ingin memprediksi apakah pelanggan puas (1) atau tidak puas (0) berdasarkan dua fitur:

-   **Waktu Tunggu** (menit): Berapa lama pelanggan menunggu pesanan.
-   **Skor Kualitas Makanan** (skala 1-10): Penilaian pelanggan terhadap makanan.

Manajemen memberikan dataset kecil berikut berdasarkan survei pelanggan:
Manajemen memberikan dataset kecil berikut berdasarkan survei pelanggan:

| Waktu Tunggu (menit) | Skor Kualitas Makanan | Kepuasan (0 = Tidak Puas, 1 = Puas) |
|-----------------------|-----------------------|-------------------------------------|
| 5                     | 8                     | 1                                   |
| 10                    | 4                     | 0                                   |
| 7                     | 6                     | 1                                   |
| 12                    | 3                     | 0                                   |
| 8                     | 7                     | 1                                   |

**Tugas Anda**:

1.  **Preprocessing Data**:
    -   Normalisasi data menggunakan StandardScaler dari _sklearn_.
    -   Jelaskan mengapa normalisasi penting untuk _neural network_.
2.  **Bangun Model Neural Network**:
    -   Gunakan MLPClassifier dengan:
        -   1 _hidden layer_ dengan 4 _node_.
        -   Fungsi aktivasi sigmoid (logistic).
        -   _Solver_ Stochastic Gradient Descent (sgd) dengan _learning rate_ 0.1.
        -   Maksimum 1000 iterasi.
        -   _Random state_ 42 untuk reproduksibilitas.
    -   Latih model menggunakan seluruh dataset (karena dataset kecil, kita tidak membagi train-test).
3.  **Evaluasi Model**:
    -   Prediksi kepuasan untuk semua data.
    -   Hitung akurasi model.
    -   Buat _confusion matrix_ untuk mengevaluasi performa.
4.  **Analisis Bobot dan Bias**:
    -   Akses bobot dan bias dari model yang telah dilatih.
    -   Jelaskan apa yang ditunjukkan oleh bobot dari _input layer_ ke _hidden layer_.
5.  **Prediksi Baru**:
    -   Prediksi kepuasan pelanggan baru dengan:
        -   Waktu Tunggu = 6 menit, Skor Kualitas Makanan = 5.
    -   Berikan probabilitas prediksi (gunakan predict_proba).
6.  **Pertanyaan Reflektif**:
    -   Mengapa inisialisasi bobot dan bias penting dalam _neural network_?
    -   Bagaimana Anda bisa meningkatkan performa model ini jika datasetnya lebih besar?

**Output yang Diharapkan**:

-   Kode Python yang lengkap untuk menyelesaikan tugas 1-5.
-   Penjelasan singkat untuk tugas 4 (analisis bobot) dan 6 (pertanyaan reflektif).
-   Hasil prediksi dan evaluasi dalam format yang jelas.

----------

### Hints

1.  **Preprocessing Data**:
    -   Gunakan StandardScaler untuk menormalkan fitur. Panggil fit_transform pada data.
    -   Normalisasi penting karena _neural networks_ sensitif terhadap skala fitur. Tanpa normalisasi, fitur dengan nilai besar (misalnya, skor kualitas) bisa mendominasi perhitungan bobot.
2.  **Bangun Model**:
    -   Inisialisasi MLPClassifier dengan parameter seperti yang diminta (hidden_layer_sizes=(4,), activation='logistic', dll.).
    -   Panggil metode fit untuk melatih model. Pastikan data sudah dinormalisasi sebelum masuk ke model.
3.  **Evaluasi Model**:
    -   Gunakan predict untuk mendapatkan prediksi kelas.
    -   Gunakan accuracy_score dan confusion_matrix dari sklearn.metrics.
    -   _Confusion matrix_ akan berbentuk 2x2 karena ini adalah klasifikasi biner.
4.  **Analisis Bobot dan Bias**:
    -   Akses bobot dengan mlp.coefs_[0] (dari _input_ ke _hidden layer_) dan bias dengan mlp.intercepts_[0].
    -   Bobot menunjukkan seberapa besar pengaruh setiap fitur (waktu tunggu, skor kualitas) terhadap _hidden node_. Bobot positif besar berarti fitur tersebut meningkatkan aktivasi _node_, sedangkan bobot negatif menekan aktivasi.
5.  **Prediksi Baru**:
    -   Normalisasi data baru menggunakan scaler yang sama (panggil transform, bukan fit_transform).
    -   Gunakan predict untuk kelas dan predict_proba untuk probabilitas.
6.  **Pertanyaan Reflektif**:
    -   Untuk inisialisasi bobot: Pikirkan tentang simetri dan konvergensi (seperti yang dijelaskan sebelumnya).
    -   Untuk meningkatkan performa: Pertimbangkan membagi data train-test, tuning parameter (GridSearchCV), atau menambah _hidden node_.

In [6]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [ ]:
# Dataset sederhana
X = np.array([[5, 8], [10, 4], [7, 6],[12, 3], [8, 7]])  # Waktu Tunggu (menit), Skor Kualitas Makanan
y = np.array([1, 0, 1, 0, 1])  # Kepuasan (0 = tidak, 1 = ya)

In [7]:
# preprocesing data
prep = StandardScaler()
scaler = prep.fit_transform(X)


In [9]:
model = MLPClassifier(hidden_layer_sizes=(4,), activation='logistic', solver='sgd', max_iter=1000, random_state=42)

In [10]:
model.fit(scaler, y)

c:\Users\ariop\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(activation='logistic', hidden_layer_sizes=(4,), max_iter=1000,
              random_state=42, solver='sgd')

In [12]:
y_pred = model.predict(scaler)
accuracy = accuracy_score(y, y_pred)
print(accuracy)

1.0


In [14]:
data_baru = np.array([[6, 5]])
data_scale = prep.fit_transform(data_baru)

pred = model.predict(data_scale)
print("Prediksi Kepuasan:", "Puas" if pred[0] == 1 else "Tidak Puas")


Prediksi Kepuasan: Puas


In [15]:
#full code
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

# Dataset
X = np.array([[5, 8], [10, 4], [7, 6], [12, 3], [8, 7]])  # Waktu Tunggu, Skor Kualitas
y = np.array([1, 0, 1, 0, 1])  # Kepuasan

# Langkah 1: Preprocessing - Normalisasi
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Langkah 242: Inisialisasi dan latih model
mlp = MLPClassifier(hidden_layer_sizes=(4,), activation='logistic', solver='sgd', 
                    learning_rate_init=0.1, max_iter=1000, random_state=42)
mlp.fit(X_scaled, y)

# Langkah 3: Evaluasi model
y_pred = mlp.predict(X_scaled)
accuracy = accuracy_score(y, y_pred)
conf_matrix = confusion_matrix(y, y_pred)

# Langkah 4: Inspeksi bobot dan bias
weights_hidden = mlp.coefs_[0]  # Bobot input ke hidden
biases_hidden = mlp.intercepts_[0]  # Bias hidden
weights_output = mlp.coefs_[1]  # Bobot hidden ke output
bias_output = mlp.intercepts_[1]  # Bias output

# Langkah 5: Prediksi pelanggan baru
new_customer = np.array([[6, 5]])  # Waktu Tunggu = 6, Skor Kualitas = 5
new_customer_scaled = scaler.transform(new_customer)
new_pred = mlp.predict(new_customer_scaled)
new_proba = mlp.predict_proba(new_customer_scaled)

# Cetak hasil
print("=== Hasil Preprocessing ===")
print("Data setelah normalisasi:\n", X_scaled)

print("\n=== Evaluasi Model ===")
print("Prediksi:", y_pred)
print("Akurasi:", accuracy)
print("Confusion Matrix:\n", conf_matrix)

print("\n=== Analisis Bobot dan Bias ===")
print("Bobot Input ke Hidden Layer:\n", weights_hidden)
print("Bias Hidden Layer:\n", biases_hidden)

print("\n=== Prediksi Pelanggan Baru ===")
print("Data Baru (setelah normalisasi):", new_customer_scaled)
print("Prediksi Kepuasan:", "Puas" if new_pred[0] == 1 else "Tidak Puas")
print("Probabilitas (Tidak Puas, Puas):", new_proba[0])

# Langkah 6: Penjelasan reflektif
print("\n=== Penjelasan Reflektif ===")
print("Analisis Bobot: Bobot dari input ke hidden layer menunjukkan pengaruh waktu tunggu dan skor kualitas terhadap hidden node. Bobot positif besar (misalnya, >1) berarti fitur tersebut sangat meningkatkan aktivasi node, sedangkan bobot negatif menekan aktivasi.")
print("Inisialisasi Bobot dan Bias: Penting untuk menghindari simetri (jika semua bobot sama, node belajar hal yang sama) dan mempercepat konvergensi. Sklearn menggunakan inisialisasi Xavier untuk memastikan skala bobot optimal.")
print("Meningkatkan Performa: Dengan dataset lebih besar, gunakan train-test split, cross-validation, dan GridSearchCV untuk tuning parameter seperti hidden_layer_sizes atau learning_rate. Menambah hidden node atau layer juga bisa membantu menangkap pola kompleks.")

=== Hasil Preprocessing ===
Data setelah normalisasi:
 [[-1.40693001  1.29399328]
 [ 0.66208471 -0.86266219]
 [-0.57932412  0.21566555]
 [ 1.4896906  -1.40182605]
 [-0.16552118  0.75482941]]

=== Evaluasi Model ===
Prediksi: [1 0 1 0 1]
Akurasi: 1.0
Confusion Matrix:
 [[2 0]
 [0 3]]

=== Analisis Bobot dan Bias ===
Bobot Input ke Hidden Layer:
 [[-1.93996627  1.73786132  1.67756199 -0.57320576]
 [ 1.61233392 -1.78302536 -2.0807444   1.17779751]]
Bias Hidden Layer:
 [ 0.4587632  -0.36994283 -0.62117399  0.46153541]

=== Prediksi Pelanggan Baru ===
Data Baru (setelah normalisasi): [[-0.99312707 -0.32349832]]
Prediksi Kepuasan: Puas
Probabilitas (Tidak Puas, Puas): [0.02061343 0.97938657]

=== Penjelasan Reflektif ===
Analisis Bobot: Bobot dari input ke hidden layer menunjukkan pengaruh waktu tunggu dan skor kualitas terhadap hidden node. Bobot positif besar (misalnya, >1) berarti fitur tersebut sangat meningkatkan aktivasi node, sedangkan bobot negatif menekan aktivasi.
Inisialisasi Bobo