In [1]:
import math

# Fungsi aktivasi sigmoid
def sigmoid(z):
    return 1 / (1 + math.exp(-z))

# Data input (setelah normalisasi: usia/100, pendapatan/100000)
x = [0.2, 0.3]  # Usia = 20, Pendapatan = 30000

# Inisialisasi bobot dan bias
# Hidden layer (2 node, masing-masing menerima 2 input)
w_hidden = [
    [0.5, 0.3],  # Bobot untuk hidden node 1
    [0.4, 0.2]   # Bobot untuk hidden node 2
]
b_hidden = [0.1, 0.1]  # Bias untuk hidden layer

# Output layer (1 node, menerima 2 input dari hidden layer)
w_output = [0.6, 0.7]  # Bobot untuk output node
b_output = 0.2         # Bias untuk output layer

# Forward Propagation
def forward_propagation(x, w_hidden, b_hidden, w_output, b_output):
    # Langkah 1: Hitung input ke hidden layer
    z_hidden = []
    a_hidden = []
    for i in range(len(w_hidden)):  # Untuk setiap node di hidden layer
        z = b_hidden[i]  # Mulai dengan bias
        for j in range(len(x)):  # Jumlahkan bobot * input
            z += w_hidden[i][j] * x[j]
        z_hidden.append(z)
        # Terapkan fungsi aktivasi sigmoid
        a_hidden.append(sigmoid(z))
    
    # Langkah 2: Hitung input ke output layer
    z_output = b_output  # Mulai dengan bias
    for i in range(len(a_hidden)):  # Jumlahkan bobot * output hidden
        z_output += w_output[i] * a_hidden[i]
    
    # Terapkan fungsi aktivasi sigmoid untuk output
    a_output = sigmoid(z_output)
    
    return z_hidden, a_hidden, z_output, a_output

# Jalankan forward propagation
z_hidden, a_hidden, z_output, a_output = forward_propagation(x, w_hidden, b_hidden, w_output, b_output)

# Cetak hasil
print("Hasil Forward Propagation:")
print(f"Input: {x}")
print(f"Z Hidden: {z_hidden}")
print(f"A Hidden (setelah sigmoid): {a_hidden}")
print(f"Z Output: {z_output}")
print(f"A Output (prediksi): {a_output}")

Hasil Forward Propagation:
Input: [0.2, 0.3]
Z Hidden: [0.29000000000000004, 0.24000000000000002]
A Hidden (setelah sigmoid): [0.5719961329315186, 0.5597136492671929]
Z Output: 0.9349972342459463
A Output (prediksi): 0.718088015291026


In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Dataset sederhana
X = np.array([[20, 30000], [30, 50000], [40, 70000]])  # Usia, Pendapatan
y = np.array([0, 1, 1])  # Membeli (0 = tidak, 1 = ya)

# Langkah 1: Normalisasi data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Langkah 2: Inisialisasi dan latih model
mlp = MLPClassifier(hidden_layer_sizes=(2,),  # 2 node di hidden layer
                    activation='logistic',   # Sigmoid
                    solver='sgd',            # Stochastic Gradient Descent
                    learning_rate_init=0.1,  # Learning rate
                    max_iter=1000,           # Jumlah iterasi
                    random_state=42)         # Untuk reproduksibilitas
mlp.fit(X_scaled, y)

# Langkah 3: Prediksi
y_pred = mlp.predict(X_scaled)
accuracy = accuracy_score(y, y_pred)

# Langkah 4: Inspeksi bobot dan bias
weights_hidden = mlp.coefs_[0]  # Bobot dari input ke hidden layer
biases_hidden = mlp.intercepts_[0]  # Bias untuk hidden layer
weights_output = mlp.coefs_[1]  # Bobot dari hidden ke output layer
bias_output = mlp.intercepts_[1]  # Bias untuk output layer

# Cetak hasil
print("Data Input (setelah normalisasi):")
print(X_scaled)
print("\nPrediksi:", y_pred)
print("Akurasi:", accuracy)
print("\nBobot Hidden Layer (input ke hidden):")
print(weights_hidden)
print("\nBias Hidden Layer:")
print(biases_hidden)
print("\nBobot Output Layer (hidden ke output):")
print(weights_output)
print("\nBias Output Layer:")
print(bias_output)

Data Input (setelah normalisasi):
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]

Prediksi: [0 1 1]
Akurasi: 1.0

Bobot Hidden Layer (input ke hidden):
[[-2.18402662  2.39284233]
 [-1.68148344  1.89788819]]

Bias Hidden Layer:
[-1.54415834  1.86387961]

Bobot Output Layer (hidden ke output):
[[-4.37824044]
 [ 5.41597574]]

Bias Output Layer:
[0.19215388]
